//! Shell integration printed by `tadoru init`. A child process cannot change
//! the parent shell's directory, so each shell gets a few lines that run
//! `tadoru pick`, read the path it prints and cd there.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use crate::names::{Names, Role};

type Error = Box<dyn std::error::Error>;

pub fn powershell(names: &Names) -> Result<String, Error> {
    let exe = exe_path()?;
    // Single quotes are the only thing that needs escaping inside '...'.
    let exe = exe.to_string_lossy().replace('\'', "''");
    let mut out = String::new();
    writeln!(out, "# tadoru: {} for PowerShell.", names.listing())?;
    out.push_str(
        r#"# Add this line to $PROFILE after zoxide init:
#   Invoke-Expression (& tadoru init powershell | Out-String)

function global:Invoke-TadoruPick {
    param([string]$Mode, [string[]]$Query)
    # The query travels in an environment variable so that the same shim
    # shape works in cmd.exe, whose argument parsing eats ^ & | on the way.
    $previousQuery = $env:TADORU_QUERY
    $env:TADORU_QUERY = ($Query -join ' ')
    $encoding = [Console]::OutputEncoding
    $exitCode = 2
    try {
        # tadoru prints UTF-8; make sure paths with non-ASCII characters
        # come back intact on consoles that default to a legacy code page.
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        $from = (Get-Location).Path
        if ($Mode -eq 'dirs' -and $Query.Count -eq 1 -and $Query[0] -eq '-') {
            if (-not $env:TADORU_PREVIOUS) { throw 'No previous tadoru directory yet.' }
            $path = $env:TADORU_PREVIOUS
            $exitCode = 0
        } else {
        $path = & '"#,
    );
    out.push_str(&exe);
    out.push_str(
        r#"' pick --mode $Mode
        $exitCode = $LASTEXITCODE
        }
        if ($exitCode -eq 0 -and $path) {
            Set-Location -LiteralPath $path -ErrorAction Stop
            if ((Get-Location).Path -ne $from) { $env:TADORU_PREVIOUS = $from }
            if (Get-Command zoxide -ErrorAction SilentlyContinue) { zoxide add -- $path 2>$null }
        } elseif ($exitCode -eq 0) {
            $exitCode = 1
        }
    } catch {
        $exitCode = 2
        Write-Error $_
    } finally {
        [Console]::OutputEncoding = $encoding
        $env:TADORU_QUERY = $previousQuery
        $global:LASTEXITCODE = $exitCode
    }
}

function global:Invoke-TadoruJump {
    param([string[]]$Query)
    $encoding = [Console]::OutputEncoding
    $exitCode = 2
    try {
        $from = (Get-Location).Path
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        if (-not $Query) {
            Set-Location -LiteralPath $HOME -ErrorAction Stop
            $exitCode = 0
        } else {
            $path = zoxide query -- @Query
            $exitCode = $LASTEXITCODE
            if ($exitCode -eq 0 -and $path) { Set-Location -LiteralPath $path -ErrorAction Stop }
            elseif ($exitCode -eq 0) { $exitCode = 1 }
        }
        if ((Get-Location).Path -ne $from) { $env:TADORU_PREVIOUS = $from }
    } catch {
        $exitCode = 2
        Write-Error $_
    } finally {
        [Console]::OutputEncoding = $encoding
        $global:LASTEXITCODE = $exitCode
    }
}

"#,
    );
    // zoxide's own z and zi are only taken away when tadoru defines its own.
    if names.zoxide() {
        out.push_str(
            r#"# zoxide init defines z / zi as aliases, and aliases win over functions.
foreach ($name in 'z', 'zi') {
    if (Test-Path "Alias:$name") { Remove-Alias -Name $name -Force -ErrorAction SilentlyContinue }
}

"#,
        );
    }
    for (name, role) in names.commands() {
        match role.mode() {
            Some(mode) => writeln!(
                out,
                "function global:{name:<2} {{ Invoke-TadoruPick {mode} $args }}"
            )?,
            None => writeln!(
                out,
                "function global:{name:<2} {{ Invoke-TadoruJump $args }}"
            )?,
        }
    }
    Ok(out)
}

/// Returns `(file name, contents)` for each PowerShell script shim. Dropped into a
/// PATH folder these work without touching the profile: a script's Set-Location
/// changes the caller's directory, unlike in POSIX shells.
pub fn powershell_scripts(names: &Names) -> Result<Vec<(String, String)>, Error> {
    let exe = exe_path()?;
    let exe = exe.to_string_lossy().replace('\'', "''");
    let mut files = Vec::new();
    for (name, role) in names.commands() {
        let Some(mode) = role.mode() else {
            files.push((format!("{name}.ps1"), POWERSHELL_JUMP_SCRIPT.to_string()));
            continue;
        };
        let summary = role.summary();
        let body = format!(
            r#"# {name} [query] - {summary}.
# Generated by "tadoru init powershell --out".
param([Parameter(ValueFromRemainingArguments)][string[]]$Query)
# A tadoru next to this script wins, so a release archive unpacked into a
# PATH folder works as is; the exe that generated the file is the fallback.
# Both names are tried because pwsh also runs where binaries carry no suffix.
$exe = $null
foreach ($candidate in 'tadoru.exe', 'tadoru') {{
    $sibling = Join-Path $PSScriptRoot $candidate
    if (Test-Path -LiteralPath $sibling -PathType Leaf) {{ $exe = $sibling; break }}
}}
if (-not $exe) {{ $exe = '{exe}' }}
$previousQuery = $env:TADORU_QUERY
$env:TADORU_QUERY = ($Query -join ' ')
$encoding = [Console]::OutputEncoding
$exitCode = 2
try {{
    [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
    $from = (Get-Location).Path
    if ('{mode}' -eq 'dirs' -and $Query.Count -eq 1 -and $Query[0] -eq '-') {{
        if (-not $env:TADORU_PREVIOUS) {{ throw 'No previous tadoru directory yet.' }}
        $path = $env:TADORU_PREVIOUS
        $exitCode = 0
    }} else {{
    $path = & $exe pick --mode {mode}
    $exitCode = $LASTEXITCODE
    }}
    if ($exitCode -eq 0 -and $path) {{
        Set-Location -LiteralPath $path -ErrorAction Stop
        if ((Get-Location).Path -ne $from) {{ $env:TADORU_PREVIOUS = $from }}
        if (Get-Command zoxide -ErrorAction SilentlyContinue) {{ zoxide add -- $path 2>$null }}
    }} elseif ($exitCode -eq 0) {{
        $exitCode = 1
    }}
}} catch {{
    $exitCode = 2
    Write-Error $_
}} finally {{
    [Console]::OutputEncoding = $encoding
    $env:TADORU_QUERY = $previousQuery
    $global:LASTEXITCODE = $exitCode
}}
"#
        );
        files.push((format!("{name}.ps1"), body));
    }
    Ok(files)
}

/// The z script. zoxide chooses the directory, so it never runs the picker.
const POWERSHELL_JUMP_SCRIPT: &str = r#"# z <keywords> - jump to a frequently used directory (zoxide history).
# Generated by "tadoru init powershell --out".
param([Parameter(ValueFromRemainingArguments)][string[]]$Query)
$encoding = [Console]::OutputEncoding
$exitCode = 2
try {
    $from = (Get-Location).Path
    [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
    if (-not $Query) {
        Set-Location -LiteralPath $HOME -ErrorAction Stop
        $exitCode = 0
    } else {
        $path = zoxide query -- @Query
        $exitCode = $LASTEXITCODE
        if ($exitCode -eq 0 -and $path) { Set-Location -LiteralPath $path -ErrorAction Stop }
        elseif ($exitCode -eq 0) { $exitCode = 1 }
    }
    if ((Get-Location).Path -ne $from) { $env:TADORU_PREVIOUS = $from }
} catch {
    $exitCode = 2
    Write-Error $_
} finally {
    [Console]::OutputEncoding = $encoding
    $global:LASTEXITCODE = $exitCode
}
"#;

pub fn write_powershell(dir: &Path, names: &Names) -> Result<Vec<PathBuf>, Error> {
    write_files(dir, powershell_scripts(names)?)
}

pub fn bash(names: &Names) -> Result<String, Error> {
    let exe = exe_path()?;
    // Forward slashes work in every bash, including the MSYS one on Windows.
    let exe = exe
        .to_string_lossy()
        .replace('\\', "/")
        .replace('\'', "'\\''");
    let mut out = String::new();
    writeln!(out, "# tadoru: {} for bash and zsh.", names.listing())?;
    out.push_str(
        r#"# Add this line to ~/.bashrc or ~/.zshrc after zoxide init:
#   eval "$(tadoru init bash)"

__tadoru_cd() {
    local before=$PWD
    cd -- "$1" || return 2
    if [ "$PWD" != "$before" ]; then export TADORU_PREVIOUS="$before"; fi
    return 0
}

__tadoru_pick() {
    local mode=$1
    shift
    if [ "$mode" = dirs ] && [ $# -eq 1 ] && [ "$1" = - ]; then
        if [ -z "${TADORU_PREVIOUS:-}" ]; then
            printf '%s\n' 'tadoru: no previous directory yet' >&2
            return 2
        fi
        __tadoru_cd "$TADORU_PREVIOUS"
        return $?
    fi
    local path
    # The query travels in an environment variable so that the same shim
    # shape works in cmd.exe, whose argument parsing eats ^ & | on the way.
    path=$(TADORU_QUERY="$*" '"#,
    );
    out.push_str(&exe);
    out.push_str(
        r#"' pick --mode "$mode") || return $?
    [ -n "$path" ] || return 1
    __tadoru_cd "$path" || return
    command -v zoxide >/dev/null 2>&1 && zoxide add -- "$path" 2>/dev/null
    return 0
}

__tadoru_jump() {
    if [ $# -eq 0 ]; then
        __tadoru_cd "$HOME" || return
        return 0
    fi
    local path
    path=$(zoxide query -- "$@") || return
    __tadoru_cd "$path"
}

"#,
    );
    if names.zoxide() {
        out.push_str(
            "# zoxide init defines z and zi itself; replace them with the tadoru versions.\nunalias z zi 2>/dev/null\n",
        );
    }
    for (name, role) in names.commands() {
        match role.mode() {
            Some(mode) => writeln!(out, "{name}() {{ __tadoru_pick {mode} \"$@\"; }}")?,
            None => writeln!(out, "{name}() {{ __tadoru_jump \"$@\"; }}")?,
        }
    }
    Ok(out)
}

/// Returns `(file name, contents)` for each cmd.exe shim.
pub fn cmd(names: &Names) -> Result<Vec<(String, String)>, Error> {
    let exe = exe_path()?;
    let exe_dir = exe
        .parent()
        .ok_or("cannot determine the directory of tadoru.exe")?
        .to_string_lossy()
        .into_owned();
    let mut files = Vec::new();
    for (name, role) in names.commands() {
        let command = match role.mode() {
            Some(mode) => format!("tadoru pick --mode {mode}"),
            None => "zoxide query -- %*".to_string(),
        };
        files.push((
            format!("{name}.cmd"),
            cmd_capture(&name, role, &exe_dir, &command),
        ));
    }
    Ok(files)
}

pub fn write_cmd(dir: &Path, names: &Names) -> Result<Vec<PathBuf>, Error> {
    write_files(dir, cmd(names)?)
}

fn write_files(dir: &Path, files: Vec<(String, String)>) -> Result<Vec<PathBuf>, Error> {
    std::fs::create_dir_all(dir)?;
    let mut written = Vec::new();
    for (name, body) in files {
        let path = dir.join(&name);
        // Windows PowerShell 5.1 reads a .ps1 without a byte order mark as the
        // system code page, so a shim holding a path with Japanese in it
        // points at nothing. PowerShell 7 and every other shell read UTF-8
        // either way, and cmd.exe would print the mark, so only .ps1 gets it.
        let bytes = if name.to_ascii_lowercase().ends_with(".ps1") {
            let mut bytes = Vec::with_capacity(body.len() + 3);
            bytes.extend_from_slice(&[0xEF, 0xBB, 0xBF]);
            bytes.extend_from_slice(body.as_bytes());
            bytes
        } else {
            body.into_bytes()
        };
        std::fs::write(&path, bytes)?;
        written.push(path);
    }
    Ok(written)
}

fn cmd_capture(name: &str, role: Role, exe_dir: &str, command: &str) -> String {
    let summary = role.summary();
    // Run directly: FOR /F's child cmd loses the exit code and reparses arguments.
    // The temporary file holds stdout only; the interactive UI stays on stderr.
    // The shortcuts follow what the script does, not what it is called, so a
    // renamed directory picker still takes - for the directory it came from.
    let shortcut = match role {
        Role::Jump => "if \"%~1\"==\"\" goto tadoru_home\n",
        Role::Dirs => "if \"%~1\"==\"-\" if \"%~2\"==\"\" goto tadoru_back\n",
        Role::Files | Role::Recent => "",
    };
    format!(r#"@echo off
rem {name} [query] - {summary}.
rem Generated by "tadoru init cmd".
setlocal DisableDelayedExpansion
set "PATH=%~dp0;{exe_dir};%PATH%"
set "TADORU_FROM=%CD%"
{shortcut}rem Capture the picker output without reparsing the query in a child cmd.
set "TADORU_QUERY=%*"
for /f "tokens=2 delims=:" %%c in ('chcp') do set "TADORU_CP=%%c"
chcp 65001 >nul
rem cmd seeds %RANDOM% from the clock when it starts, so shells opened in the
rem same second draw the same names. mkdir fails on a name already taken,
rem even by a shell racing this one, and then the next name is tried.
set "TADORU_TRIES=0"
:tadoru_temp
set /a TADORU_TRIES+=1
if %TADORU_TRIES% gtr 20 goto tadoru_no_temp
set "TADORU_TEMP=%TEMP%\tadoru-%RANDOM%-%RANDOM%"
mkdir "%TADORU_TEMP%" >nul 2>nul || goto tadoru_temp
set "TADORU_RESULT=%TADORU_TEMP%\path.txt"
{command} > "%TADORU_RESULT%"
set "TADORU_EXIT=%ERRORLEVEL%"
set "TADORU_PATH="
if "%TADORU_EXIT%"=="0" for /f "usebackq delims=" %%p in ("%TADORU_RESULT%") do set "TADORU_PATH=%%p"
rmdir /s /q "%TADORU_TEMP%" >nul 2>nul
chcp %TADORU_CP% >nul
if not "%TADORU_EXIT%"=="0" exit /b %TADORU_EXIT%
if not defined TADORU_PATH exit /b 1
:tadoru_move
if "%TADORU_PATH:~0,2%"=="\\" goto tadoru_share
cd /d "%TADORU_PATH%"
if errorlevel 1 exit /b 2
zoxide add -- "%TADORU_PATH%" 2>nul
if /i "%TADORU_FROM%"=="%CD%" set "TADORU_FROM=%TADORU_PREVIOUS%"
endlocal & cd /d "%TADORU_PATH%" && set "TADORU_PREVIOUS=%TADORU_FROM%"
if errorlevel 1 exit /b 2
exit /b 0
:tadoru_share
rem cmd cannot cd into a \\server\share path. pushd maps a free drive
rem letter to the share and goes there; popd comes back and frees it.
if not exist "%TADORU_PATH%\" exit /b 2
zoxide add -- "%TADORU_PATH%" 2>nul
endlocal & pushd "%TADORU_PATH%" && set "TADORU_PREVIOUS=%TADORU_FROM%"
if errorlevel 1 exit /b 2
exit /b 0
:tadoru_no_temp
chcp %TADORU_CP% >nul
echo tadoru: cannot create a temporary folder in "%TEMP%" 1>&2
exit /b 2
:tadoru_back
if not defined TADORU_PREVIOUS (
    echo tadoru: no previous directory yet 1>&2
    exit /b 2
)
set "TADORU_PATH=%TADORU_PREVIOUS%"
goto tadoru_move
:tadoru_home
set "TADORU_PATH=%USERPROFILE%"
goto tadoru_move
"#).replace('\n', "\r\n")
}

fn exe_path() -> Result<PathBuf, Error> {
    let exe = std::env::current_exe()?;
    Ok(std::path::absolute(exe)?)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn powershell_shims_carry_a_byte_order_mark_and_cmd_files_do_not() {
        let dir = crate::testing::temp_dir().join(format!("tadoru-shimenc-{}", std::process::id()));
        let files = vec![
            ("c.ps1".to_string(), "# ps\n".to_string()),
            ("c.cmd".to_string(), "@echo off\n".to_string()),
        ];
        let written = write_files(&dir, files).unwrap();
        assert_eq!(written.len(), 2);

        // Windows PowerShell 5.1 reads a .ps1 without the mark as the system
        // code page, so the path to the executable inside it resolves to
        // nothing when it has Japanese in it.
        let ps = std::fs::read(dir.join("c.ps1")).unwrap();
        assert_eq!(&ps[..3], &[0xEF, 0xBB, 0xBF]);
        // cmd.exe has no such problem and would echo the mark as characters.
        let cmd = std::fs::read(dir.join("c.cmd")).unwrap();
        assert_eq!(&cmd[..3], b"@ec");

        crate::testing::remove_tree(&dir);
    }

    #[test]
    fn powershell_defines_the_four_commands_and_drops_aliases() {
        let out = powershell(&Names::default()).unwrap();
        for f in [
            "function global:c ",
            "function global:cf",
            "function global:z ",
            "function global:zi",
        ] {
            assert!(out.contains(f), "missing {f}");
        }
        assert!(out.contains("Remove-Alias"));
        assert!(out.contains("param([string]$Mode, [string[]]$Query)"));
    }

    #[test]
    fn bash_defines_the_four_commands_with_a_slash_path() {
        let out = bash(&Names::default()).unwrap();
        for f in ["\nc() {", "\ncf() {", "\nz() {", "\nzi() {"] {
            assert!(out.contains(f), "missing {f}");
        }
        assert!(out.contains("unalias z zi"));
        let exe_line = out.lines().find(|l| l.contains("pick --mode")).unwrap();
        assert!(
            !exe_line.contains('\\'),
            "exe path must use forward slashes: {exe_line}"
        );
    }

    #[test]
    fn powershell_scripts_prefer_the_exe_next_to_them() {
        let files = powershell_scripts(&Names::default()).unwrap();
        let names: Vec<&str> = files.iter().map(|(n, _)| n.as_str()).collect();
        assert_eq!(names, ["c.ps1", "cf.ps1", "zi.ps1", "z.ps1"]);
        let (_, c) = &files[0];
        // Both names, so a shim written on one platform still finds the
        // binary sitting beside it on another.
        assert!(c.contains("foreach ($candidate in 'tadoru.exe', 'tadoru')"));
        assert!(c.contains("Join-Path $PSScriptRoot $candidate"));
        assert!(c.contains("pick --mode dirs"));
        assert!(c.contains("ValueFromRemainingArguments"));
    }

    #[test]
    fn cmd_emits_four_files_with_the_exe_dir_on_path() {
        let files = cmd(&Names::default()).unwrap();
        let names: Vec<&str> = files.iter().map(|(n, _)| n.as_str()).collect();
        assert_eq!(names, ["c.cmd", "cf.cmd", "zi.cmd", "z.cmd"]);
        let (_, c) = &files[0];
        assert!(c.contains("tadoru pick --mode dirs"));
        assert!(c.contains("set \"TADORU_QUERY=%*\""));
        assert!(
            c.contains("set \"PATH=%~dp0;"),
            "the shim folder must come first on PATH"
        );
        assert!(!c.contains("'\""), "exe must not be quoted inside for /f");
        assert!(
            c.split('\n').all(|l| l.is_empty() || l.ends_with('\r')),
            "cmd files use CRLF"
        );
    }

    #[test]
    fn a_chosen_name_replaces_c_everywhere_and_keeps_its_shortcuts() {
        let names = Names::new(Some("j".into()), false).unwrap();
        let ps = powershell(&names).unwrap();
        assert!(
            ps.starts_with("# tadoru: j / jf / zi / z for PowerShell."),
            "{ps}"
        );
        assert!(ps.contains("function global:j "), "{ps}");
        assert!(ps.contains("function global:jf"), "{ps}");
        assert!(!ps.contains("function global:c "));
        assert!(!ps.contains("function global:cf"));

        let sh = bash(&names).unwrap();
        assert!(sh.contains("\nj() {") && sh.contains("\njf() {"), "{sh}");
        assert!(!sh.contains("\nc() {"));

        let scripts: Vec<String> = powershell_scripts(&names)
            .unwrap()
            .into_iter()
            .map(|(name, _)| name)
            .collect();
        assert_eq!(scripts, ["j.ps1", "jf.ps1", "zi.ps1", "z.ps1"]);

        // cmd.exe's shortcuts follow what a script does, so the renamed
        // directory picker still takes - and z still goes home.
        let files = cmd(&names).unwrap();
        let body = |name: &str| {
            files
                .iter()
                .find(|(file, _)| file == name)
                .map(|(_, body)| body.clone())
                .unwrap()
        };
        assert!(body("j.cmd").contains("goto tadoru_back"));
        assert!(!body("j.cmd").contains("goto tadoru_home"));
        assert!(!body("jf.cmd").contains("goto tadoru_back"));
        assert!(body("z.cmd").contains("goto tadoru_home"));
    }

    #[test]
    fn keeping_zoxide_leaves_z_and_zi_and_their_aliases_alone() {
        let names = Names::new(None, true).unwrap();
        let ps = powershell(&names).unwrap();
        assert!(!ps.contains("function global:z "));
        assert!(!ps.contains("function global:zi"));
        assert!(!ps.contains("Remove-Alias"));
        let sh = bash(&names).unwrap();
        assert!(!sh.contains("unalias"));
        assert!(!sh.contains("\nz() {") && !sh.contains("\nzi() {"));
        let files: Vec<String> = cmd(&names)
            .unwrap()
            .into_iter()
            .map(|(name, _)| name)
            .collect();
        assert_eq!(files, ["c.cmd", "cf.cmd"]);
    }
}
